spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
server:
  port: 8666
  servlet:
    context-path: /api
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn